---
title: "Оптимизация содержания и тактики хирургического лечения пострадавших с изолированными неосложненными «взрывными» переломами грудных и поясничных позвонков: дисс. … канд. мед. наук: 14.01.15"
author: "Паршин Михаил Сергеевич"
output:
  word_document:
    keep_md: yes
    toc: yes
    toc_depth: 3
    reference_docx: Normal.dotm
  html_notebook:
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: xt-ao-type-a.bib
csl: gost-7-1-2003.csl
---

# Глава 1. Оптимизация содержания и тактики хирургического лечения пострадавших с изолированными неосложненными «взрывными» переломами грудных и поясничных позвонков: состояние проблемы (обзор литературы)

## 1.1 Анализ структуры входящего потока пациентов с изолированными «взрывными» переломами грудных и поясничных позвонков в общей структуре пострадавших с позвоночно-спинномозговой травмой, госпитализируемых в профильные специализированные хирургические отделения, и структура хирургических вмешательств, выполненных у таких пострадавших: состояние проблемы (обзор литературы к 1-му этапу диссертационной работы)

### 1.1.1 Структура входящего потока пострадавших с позвоночно-спинномозговой травмой, госпитализируемых в профильные специализированные хирургические отделения

Доля пациентов с изолированными «взрывными» переломами грудных и поясничных позвонков в общей структуре пострадавших с позвоночно-спинномозговой травмой, госпитализируемых в профильные специализированные хирургические отделения.

### 1.1.2 Структура хирургических вмешательств, выполненных у пострадавших с изолированными «взрывными» переломами грудных и поясничных позвонков

Структура хирургических доступов, применяемых в лечении таких пострадавших.

Типовые варианты хирургических доступов, применяемых в лечении таких пострадавших.

Пять групп доступов как типовые варианты хирургических доступов: из традиционного открытого переднего доступа, из традиционного открытого заднего доступа, из заднего малоинвазивного доступа, из комбинированного открытого переднего и заднего доступа, из комбинированного открытого переднего и малоинвазивного заднего доступа.

Содержание оперативных пособий для пяти вышеуказанных способов инструментальной фиксации позвоночника.

Типовые варианты оперативных пособий для пяти вышеуказанных способов инструментальной фиксации позвоночника.

## 1.2 Изучение клинических показателей лечения пациентов с изолированными «взрывными» переломами грудных и поясничных позвонков в условиях профильного хирургического стационара и после выписки из него в пяти выделенных группах: состояние проблемы (обзор литературы ко 2-му этапу диссертационной работы)

### 1.2.1 Клинические характеристики оказанных оперативных пособий, влияющие на общее состояние прооперированного пациента, динамику течения раневого процесса и временные показатели стационарного лечения

Длительность операции.

[@Labbe2018] изучили длительность операций из малоинвазивных задних доступов. Изучемые повреждения были у 20 из 24 пациентов, однако авторы не представили результаты лечения, стратифированные по типу перелома, а также не представили объединенные показатели по выборке, поскольку выполняли сравнительный анализ двух минимально инвазивных методик, возможен пересчет.

По данным [@Kocis2018], операции из задних доступов были непродолжительны, и длительность операции не отличалась при открытых и малоинвазивных задних операциях (в среднем 52,0 минут против 49,7 минут; p = 0,376; N = 46).

Величина периоперационной кровопотери.

По данным [@Kocis2018] периоперационная кровопотеря при операциях из задних доступов была невысокой, при этом при операциях из открытых задних доступов была выше, чем при малоинвазивных задних операциях (в среднем 328,7 мл против 29,0 мл; p < 0,005; N = 46).

В работе [@Chang2018] изучили результаты лечения из малоинвазивных и открытых задних доступов. 46 из 62 пациентов имели повреждения искомого типа, при этом оставшиеся 16 из 62 пациентов отличались наличием неврологического дефицита уровня D по ASIA, сведения для стратификации результатов не представлены. Интраоперационная кровопотеря не была высокой, при этом была ниже в группе малоинвазивного заднего доступа (194,0 ± 7,5 мл против 256,0 ± 14,5 мл; p < 0,001). Кровопотеря по дренажам также была невысокой и была меньше в группе малоинвазивного лечения (94,0 ± 22,0 мл против 160,0 ± 19,0 мл; p < 0,001).

Нуждаемость в послеоперационном наблюдении и лечении в условиях ОРИТ.

Длительность пребывания в ОРИТ.

Нуждаемость в гемотрансфузионной терапии.

Величина гемотрансфузионной терапии.

Частота местных инфекционных осложнений.

Характер местных инфекционных осложнений.

Частота общих инфекционных осложнений.

Характер общих инфекционных осложнений.

### 1.2.2 Временные показатели лечения

Продолжительность послеоперационного периода.

Общая длительность стационарного лечения.

### 1.2.3 Полнота решения лечебных задач в результате оказанных оперативных пособий

[@LaMaida2019] изучили угол кифотической деформации, высоту и процент компрессии тела позвонка в раннем послеоперационном периоде при операциях из открытых задних доступов. Только у 9 из 20 пациентов были повреждения изучаемого вида, и авторы представили показатели деформации без стратификации по типу перелома, однако представили также и первичные данные, в связи с чем возможен пересчет.

[@Labbe2018] получили данные об углах кифотической деформации тела позвонка, углах Гарднера и Кобба в раннем периоде после операций из малоинвазивных задних доступов. Изучаемые повреждения были у 20 из 24 пациентов, однако авторы не представили результаты лечения, стратифированные по типу перелома, а также не представили объединенные показатели по выборке, поскольку выполняли сравнительный анализ двух минимально инвазивных методик, возможен пересчет.

По данным [@Kocis2018] коррекция угла Кобба после операции из заднего доступа составляла несколько градусов и не отличалась при открытых и малоинвазивных задних операциях (в среднем 3,8 против 4,5 градусов; p = 0,895; N = 46).

Восстановление формы позвоночного столба.

Восстановление баланса позвоночного столба.

Восстановление просвета позвоночного канала.

Вид и качество реконструкции передней колонны позвоночного столба.

Вид и качество фиксации позвоночного столба.

### 1.2.4 Показатели состояния пострадавших после выписки из стационара

Наличие болевого синдрома.

Вид (локальный или корешковый) болевого синдрома.

Динамика болевого синдрома.

[@Labbe2018] собрали данные об уровне и динамике боли по шкале ВАШ в раннем периоде после операций из малоинвазивных задних доступов. Повреждения изучаемого вида были у 20 из 24 пациентов, однако авторы не представили результаты лечения, стратифированные по типу перелома, а также не представили объединенные показатели по выборке, поскольку выполняли сравнительный анализ двух минимально инвазивных методик, возможен пересчет.

[@Chang2018] изучили уровень и динамику боли по ВАШ (0–10 баллов) при операциях из малоинвазивных и открытых задних доступов. 46 из 62 пациентов имели повреждения искомого типа, при этом оставшиеся 16 из 62 пациентов отличались наличием неврологического дефицита уровня D по ASIA, сведения для стратификации результатов не представлены. Через 2 недели после операции (первая точка наблюдения) уровень боли в группе малоинвазивного лечения был довольно высоким, при этом был схожим с таковым при открытых операциях (6,0 ± 1,0 против 6,0 ± 2,0; p = 0,029), в динамике он снижался без существенных различий между группами до полного исчезновения боли через 24 месяца после операции (последняя точка): в обеих группах по 0,0 ± 1,0; p = 0,536.

Частота местных инфекционных осложнений.

Характер местных инфекционных осложнений.

В работе [@Chang2018] при сравнении малоинвазивных и открытых задних доступов (46 из 62 пациентов имели повреждения искомого типа, при этом оставшиеся 16 из 62 пациентов отличались наличием неврологического дефицита уровня D по ASIA, сведения для стратификации результатов не представлены) частота местных инфекционных осложнений не отличалась, составляя в целом около одного случая из десяти (поверхностная инфекция: 2 из 30 против 5 из 32; p = 0,476; 1 из 30 против 3 из 32; p = 0,652).

В работе [@Kocis2018] у 46 пациентов, оперированных из открытых либо малоинвазивных задних доступов, не встретилось ни одной инфекции операционной раны за период наблюдения (1 год).

Частота общих инфекционных осложнений.

Характер общих инфекционных осложнений.

Динамика качества жизни в сроки 3, 6, 12 и 24 мес. после операции.

В работе [@Chang2018] изучили результаты лечения из малоинвазивных и открытых задних доступов. 46 из 62 пациентов имели повреждения искомого типа, при этом оставшиеся 16 из 62 пациентов отличались наличием неврологического дефицита уровня D по ASIA, сведения для стратификации результатов не представлены. Авторы привели качество жизни по шкале Освестри на всех искомых точках послеоперационного наблюдения, в целом оно было снижено вполне умеренно, и при оценке через 1 месяц после операции качество жизни в группе малоинвазивных операций было несколько лучше (32,5 ± 5,0 против 37,5 ± 5,0; p < 0,001). На остальных же точках показатели были схожими в группах, в целом по выборке постепенно улучшаясь в динамике.

### 1.2.5 Анатомо-функциональные результаты лечения пострадавших через 24 месяца после операции

Частота потери коррекции деформации позвоночного столба.

Величина потери коррекции деформации позвоночного столба.

В работе [@Chang2018] изучили результаты лечения из малоинвазивных и открытых задних доступов. 46 из 62 пациентов имели повреждения искомого типа, при этом оставшиеся 16 из 62 пациентов отличались наличием неврологического дефицита уровня D по ASIA, сведения для стратификации результатов не представлены. Авторы привели углы Гарднера ([@Song2009]) после операции через 2 недели (4,3 ± 5,6 градуса против 4,8 ± 5,1 градуса; p = 0,375) и через 24 месяца (4,2 ± 5,1 градуса против 4,7 ± 4,8 градуса; p = 0,485); таким образом, деформация не была выраженной, потери коррекции в целом не наблюдалось и отличий между группами по потери коррекции не было.

Состоятельность спондилодеза.

Качество жизни. По шкале качества жизни Освестри (Oswestry Disability Index – ODI).

В работе [@Chang2018] изучили результаты лечения из малоинвазивных и открытых задних доступов. 46 из 62 пациентов имели повреждения искомого типа, при этом оставшиеся 16 из 62 пациентов отличались наличием неврологического дефицита уровня D по ASIA, сведения для стратификации результатов не представлены. Качество жизни прооперированных по шкале Освестри через 2 года после операции было неплохим, в группе малоинвазивного заднего доступа не отличалось от такового в группе открытого заднего доступа (17,5 ± 2,5 против 18,8 ± 6,9; p = 0,924).

Качество жизни. По модифицированной шкале Macnab.

Доли больных, вернувшихся к дотравматическому уровню трудовой активности.

## 1.3 Рекомендации по выбору оптимальных вариантов хирургического лечения пострадавших с изолированными неосложненными «взрывными» переломами грудных и поясничных позвонков применительно к конкретным условиям оказания специализированной медицинской помощи: состояние проблемы (обзор литературы к 3-му этапу диссертационной работы)

Сведения по уже имеющимся рекомендательным документам того же плана.

В плане выбора доступа (передний, задний или комбинированный) с позиций клинических и неврологических результатов Американский Конгресс неврологических хирургов высказывает сдержанную рекомендацию считать доступ выбором хирурга, поскольку, вид доступа на них, «похоже, не влияет» ([@Anderson2019], [@OToole2019]). При этом с позиций лучевых результатов и осложнений хирургам также рекомендуется делать выбор самостоятельно, однако в этом случае Конгресс дает такую рекомендацию уже по причине противоречивости научных данных. На уровне сдержанной рекомендации тот же коллектив предлагает хирургам принять во внимание, что при задних доступах открытые и чрескожные методики — в равной мере допустимы, поскольку в исследованиях продемонстрировали схожие клинические результаты. В части содержания оперативного пособия Конгресс рекомендует хирургам учитывать, причем здесь рекомендует настоятельно, что выполнение спондилодеза в дополнение к инструментальной фиксации в исследованиях не продемонстрировало отличий клинических и лучевых результатов ([@Chi2019], [@OToole2019]).

Немецкое общество ортопедии и травмы ([@Verheyden2018]) выражает позицию о возможности использования как передних, так и задних доступов, при этом минимально инвазивные доступы называют предпочтительными. Показанием к операции считают повреждения с разницей между углом деформации (Гарднера либо, если невозможно рассчитать, Кобба) и физиологическим показателем сагиттальной ангуляции на этом уровне более 15–20 градусов, либо наличие сколиоза более 10 градусов. Также рекомендуют принимать во внимание степень расхождения костных фрагментов тела позвонка и величину стеноза позвоночного канала. При повреждениях типа A3, как минимум, операция из заднего доступа подлежит выполнению, в принципе же возможны различные варианты. При повреждениях типа A4 рекомендуют рассмотреть вопрос о реконструкции тела позвонка более пристально.

## 1.4 Резюме

Изолированные неосложненные травматические взрывные переломы грудных и поясничных позвонков составляют основательную долю в общей структуре пострадавших с позвоночно-спинномозговой травмой, госпитализируемых в профильные специализированные хирургические отделения. Структура хирургического лечения весьма разнообразна, однако предложенные типовые варианты хирургического лечения действительно охватывают большинство выполняемых хирургических вмешательств, если не считать пункционных методик. При этом в литературе выделены и хорошо прослеживаются и типовые варианты хирургических пособий.

Результаты лечения в пяти выделенных типовых группах изучены неравномерно с хорошо ощутимым преобладанием работ по вмешательствам из открытых и малоинвазивных задних доступов. Результаты хирургического лечения, будучи рассмотрены в изоляции, в целом достаточно неплохи, при этом ни один из типовых вариантов не проявляет каких-либо принципиальных преимуществ или недостатков. Немаловажно, что минимально инвазивные технологии демонстрируют в целом не худшие результаты по сравнению с традиционными методиками, а иногда все же и превосходят их по ближайшим результатам лечения.

Рекомендаций по выбору оптимальной тактики хирургического лечения — довольно много в литературе. В целом они варьируют от довольно подробных прескриптивных руководств по принятию хирургических решений до рекомендаций весьма общего характера, оставляющих практически все решения на выбор хирурга. К сожалению, нельзя не отметить, что нарастание доказательной базы и внимания к ее анализу на сегодняшний день сопряжено здесь именно со снижением прескриптивности рекомендаций ввиду отсутствия надежных научных данных по многим вопросам, в связи с чем современные методы выработки рекомендаций консенсусом группы экспертов остаются высоко актуальными в этой сфере. Вместе с тем, отсутствие адаптации к условиям оказания хирургической помощи является общей чертой имеющихся рекомендаций, что, безусловно, дополнительно ограничивает их практическое значение.

## Исключены по полному тексту

[@Gumussuyu2018] сравнили результаты лечения при открытом заднем и комбинированном открытом переднем с открытым задним доступах у пострадавших с типом B + A (в критериях включения: взрывной перелом, повреждение заднего связочного комплекса). Исключено по полному тексту, так как другой тип повреждения.

[@Yu2019] изучили результаты лечения с применением малоинвазивных передних доступов. Исключено по полному тексту, поскольку такая группа отсутствует в диссертационном материале.

[@Seo2019] изучили результаты лечения с применением задних доступов, одним из критериев включения было 4 и более баллов по TLICS, в то время как рассматриваемый вид повреждений соответствует не более 4 баллов. Исключено по полному тексту по несовпадению популяции.

## Ожидают рассмотрения

[@Yin2019] оценили скрытую периоперационную кровопотерю. Полный текст недоступен.

[@Vicenty2018] изучили результаты лечения из задних доступов. Полный текст недоступен.

[@Lorente2019], [@Paredes2018]  сравнили результаты лечения при открытых задних и малоинвазивных доступах. Полные тексты недоступны.

[@Wang2018], [@Shao2018] изучили результаты лечения из малоинвазивных задних доступов системами наружной фиксации. Полные тексты на китайском.

# Список литературы
